// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateInfoButton('info', { foregroundStyle: 'black', onclick: 'showBack', frontID: 'front', backgroundStyle: 'black' });
    CreateText('text', { text: 'Photocast URL' });
}
window.addEventListener('load', setupParts, false);
