// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateHorizontalSlider('horizontalSlider', { continuous: true, onchange: 'updateCompositionTransform', currentValue: 1 });
    CreateVerticalSlider('verticalSlider', { continuous: true, onchange: 'updateCompositionWatermark', currentValue: 0.7 });
    CreateText('helloText', { text: 'Quartz Composer 3d Graph' });
    CreateText('statusText', { text: unescape('Loading data from...%0AURL') });
    CreateInfoButton('info', { foregroundStyle: 'black', onclick: 'showBack', frontID: 'front', backgroundStyle: 'black' });
}
window.addEventListener('load', setupParts, false);
