// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { foregroundStyle: 'black', onclick: 'showBack', backgroundStyle: 'black', frontID: 'front' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
}
window.addEventListener('load', setupParts, false);
